import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import { RiMoonClearLine } from "react-icons/ri";
import { FaGithub } from "react-icons/fa";
import { ImLinkedin } from "react-icons/im";
import { FaFacebook } from "react-icons/fa";
import { AiFillMediumSquare } from "react-icons/ai";

// profile
import profileImage from "../public/p2.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
      </Head>
      <main className="font-Poppins bg-yellow-50 min-h-screen px-10">
        <section>
          {/* nav section */}
          <nav className="py-10 flex justify-between ">
            <h1 className="text-sm">Developed by Shan</h1>
            <ul className="flex items-center">
              <li>
                <RiMoonClearLine className="cursor-pointer text-xl mx-5" />
              </li>
              <li>
                <a
                  className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md"
                  href="#"
                  download={"resume"}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero section */}
          <div className="text-center p-10">
            <h1 className="text-5xl font-bold">Shan Rathnayake</h1>
            <h3 className="text-2xl py-4">Full-Stack Developer</h3>
            <p className="text-sm py-4 text-gray-400">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Quibusdam optio harum sint numquam odit quas odio consectetur,
              suscipit earum aliquid aspernatur placeat! Molestiae repellat sunt
              non soluta quibusdam, dicta aut!
            </p>
          </div>

          {/* social links */}
          <div className="text-3xl flex justify-center gap-10 text-gray-600">
            <a href="">
              <FaGithub />
            </a>
            <a href="">
              <ImLinkedin />
            </a>
            <a href="">
              <FaFacebook />
            </a>
            <a href="">
              <AiFillMediumSquare />
            </a>
          </div>

          {/* profile */}
          <div className="w-80 h-80 p-5 mt-7 m-auto relative bg-gradient-to-b from-yellow-200 rounded-full">
            <Image
              src={profileImage}
              alt="Profile image"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
      </main>
    </div>
  );
}
